# Generated by Django 2.0.1 on 2018-04-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainEndPoint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='user',
            new_name='owner',
        ),
    ]
